language: kotlin
sudo: false
jdk:
  - openjdk11
install:
  - ./gradlew clean
  - travis_wait 50 ./gradlew :uoms:build
script:
  - ./gradlew check
cache:
  directories:
    - $HOME/.gradle
#    - $HOME/.konan